name: xwayland-kiosk-helper
version: 1
summary: Helper to run X11 apps on a Wayland kiosk
description: |
  Helper to run X11 applications on a Wayland kiosk, using Xwayland
  and a basic window manager to enforce fullscreen kiosk behaviour.
  .
  Can works in collaboration with the snapcraft desktop helpers:
  https://github.com/ubuntu/snapcraft-desktop-helpers
  .
  Usage:
    1. add "after: [desktop-<technology>, xwayland-kiosk]" to your
       launcher (selecting the correct toolkit technology)
    2. prepend your command with "desktop-launch xwayland-kiosk-launch", like:
       commands: "desktop-launch xwayland-kiosk-launch $SNAP/path/to/foo"
    3. give a hint for what X11 surface should be fullscreen.
       Below "commands" add:
       environment:
         FULLSCREEN_WINDOW_HINT='window_role="browser-window"'
       There are various matcher criteria that can be used, reference:
       https://i3wm.org/docs/userguide.html#_list_of_commands
    5. [EDGE Core only] for full confinement need to add these plugs and slots
       slots: [ x11 ]
       plugs: [ x11-plug, opengl ]
      
       plugs:
         x11-plug: # because cannot have identical plug/slot name in same yaml.
           interface: x11

confinement: strict

parts:
  xwayland-kiosk-helper:
    plugin: cmake
    source: xwayland-preload
    build-packages:
      - build-essential
    stage-packages:
      - xwayland
      - i3
      - libegl1-mesa
      - libgl1-mesa-glx
    prime:
      - bin/xwayland-kiosk-launch
      - lib/libxwayland-preload.so
      - usr/bin/Xwayland
      - usr/bin/xkbcomp
      - usr/bin/i3
      - usr/lib/xorg/*
      - usr/lib/*/lib*
      - -usr/lib/*/libperl*
      - usr/lib/*/dri
      - usr/lib/*/mesa
      - usr/lib/*/mesa-egl
      - usr/share/fonts
      - usr/share/libdrm
      - usr/share/glib-2.0
      - usr/share/X11
      - etc/drirc
      - etc/fonts
      - etc/i3
      - etc/X11
      

